/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_DAO extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_DAO
     */
    public Inicio_DAO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/programador.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 150);

        jLabel2.setText("Estado Civil");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 20, 80, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Masculino", "Feminino" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(570, 40, 90, 22);

        jLabel3.setText("RG:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 70, 21, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Casado", "Solteiro", "Viúvo", " " }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(680, 40, 71, 22);

        jLabel4.setText("Sexo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 20, 38, 16);

        jLabel5.setText("Nome Completo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 20, 110, 16);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 40, 370, 22);

        jLabel6.setText("Data Nascimento:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 110, 101, 16);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 40, 280, 22);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(180, 90, 280, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 130, 130, 22);

        jLabel10.setText("CPF:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(470, 70, 27, 16);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(470, 90, 290, 22);

        jLabel8.setText("Nacionalidade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 110, 100, 16);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(320, 130, 140, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SP", "RJ", "MG" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(700, 130, 45, 22);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(470, 130, 210, 22);

        jLabel7.setText("Naturalidade:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 110, 80, 16);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(10, 180, 300, 22);

        jLabel9.setText("Endereço:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 160, 70, 16);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(320, 180, 140, 22);

        jLabel11.setText("Numero:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 160, 60, 16);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(470, 180, 300, 22);

        jLabel12.setText("Complemento:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(470, 160, 90, 16);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(10, 230, 300, 22);

        jLabel13.setText("Municipio:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 210, 80, 16);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(320, 230, 140, 22);

        jLabel14.setText("Bairro:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 210, 48, 16);

        jLabel15.setText("UF:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(700, 110, 20, 16);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(694, 230, 70, 22);
        jPanel1.add(jTextField13);
        jTextField13.setBounds(470, 230, 210, 22);

        jLabel16.setText("CEP:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(470, 210, 27, 16);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(10, 290, 170, 22);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(190, 290, 140, 22);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(340, 290, 120, 22);

        jLabel17.setText("Telefone:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 270, 60, 16);

        jLabel18.setText("Celular:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(190, 270, 45, 16);

        jLabel19.setText("E-mail:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(340, 270, 41, 16);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(470, 290, 300, 22);

        jLabel20.setText("Cadastro em:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(470, 270, 90, 16);

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Cadastrar");
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 340, 90, 25);

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setText("Limpar");
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 340, 71, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(796, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_DAO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
